default_args:
  start_date: '2021-05-20'
  num_task_retries: 3
  retry_delay: 1
  execution_timeout: 60
  depends_on_past: True
  owner: 'airflow'
  email:
    - 'airflow@example.com'
dag_args:
  schedule_interval: "0 0 * * *"
  dagrun_timeout: 30
tasks_args:
  local_docker_data_volume: '/home/sergey/Work/courses/made/semester-2/ml-in-prod/sergey-msu/airflow_ml_dags/data'
  download_data_hive:
    name: 'hive_data'
    output_path: '/data/raw/{{ ds }}/hive'
    seed: 1
  download_data_clickhouse:
    name: 'clickhouse_data'
    output_path: '/data/raw/{{ ds }}/clickhouse'
    seed: 2
  download_data_mongo:
    name: 'mongo_data'
    output_path: '/data/raw/{{ ds }}/mongo'
    seed: 3
  merge_data:
    input_paths:
      - '/data/raw/{{ ds }}/hive'
      - '/data/raw/{{ ds }}/clickhouse'
      - '/data/raw/{{ ds }}/mongo'
    output_path: '/data/raw/{{ ds }}'
  clean_data:
    input_paths:
      - '/data/raw/{{ ds }}/hive'
      - '/data/raw/{{ ds }}/clickhouse'
      - '/data/raw/{{ ds }}/mongo'
