# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MADE-2021 Test ML App

on:
  push:
    branches: [ homework1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Requirements installation
        working-directory: ./ml_project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Flake8 code styling
        working-directory: ./ml_project
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Unit and Integration tests
        working-directory: ./ml_project
        run: |
          pytest
